export const facts =[
    
  {
        id: 'facts1',
        name: 'Piastre (piasse)',
        p1: "In Quebec, the word piastre (pronounced piasse) is often used as a synonym for the word dollar.",
        p2: "The word \"piastre\", was used in Nouvelle-France and in several colonies, then it was officially replaced by the word \"dollar\", the official monetary unit of Canada.",
        p3: "Several popular expressions are constructed with the word piastre.",
        ex1:"Faire la piastre: to make a lot of money",
        ex2:"Poser une question à cent piastres: to ask a question whose answer is difficult to find.",        
        src: 'https://carnaval.qc.ca/en/',
        img:'./assets/images-main/facts/dollar.jpg'
    },
    {
        id: 'facts2',
        name: 'Les dépanneurs',
        p1: "In Quebec, there are approximately 6,000 convenience stores(les dépanneurs).",
        p2: "These small shops \"on the corner of the street\" are open late at night.",
        p3: "They mainly sell basic food products (salt, milk...), drinks (juice, soft drinks, mineral water...), as well as alcohol, cigarettes, etc.",
        ex1:"",
        ex2:"",
        src: 'https://carnaval.qc.ca/en/',
        img:'./assets/images-main/facts/depanneur.jpg'
    },
    {
        id: 'facts3',
        name: 'Troquer',
        p1: "In July 2005, on a classifieds website,The Canadian Kyle Macdonald offered a red paper clip to exchange for another object.",
        p2: "He then obtains a fish-shaped pen. He then swaps the pen for a door handle, then the handle for a barbecue.",
        p3: "A year and thirteen barters later, his red paper clip becomes a house in Kipling, Saskatchewan.",
        ex1:"Troquer: to exchange one good or service for another good or service.",
        ex2:"",
        src: 'https://carnaval.qc.ca/en/',
        img:'./assets/images-main/facts/clip.jpg'
    },
    {
        id: 'facts4',
        name: 'Le chiac',
        p1: "Chiac is a variant of French spoken in New Brunswick, mainly in Moncton and in the southeast of the province.",
        p2: "This mixture of French and English inspires several singers (Radio, Lisa LeBlanc, Les Hay Babies) and writers (Jean Babineau, France Daigle), who choose this language to highlight their identity.",
        p3: "",
        ex1:"",
        ex2:"",
        src: 'https://carnaval.qc.ca/en/',
        img:'./assets/images-main/facts/chiac.jpg'
    },
    {
        id: 'facts5',
        name: 'Les Félix',
        p1: "\"Les Félix\" are prizes awarded to artists who work in the field of music in Quebec.",
        p2: "\"Les Félix\", named in honor of the singer-songwriter Félix Leclerc, are distributed every year in the context of the Gala de l'ADISQ.",
        p3: "",
        ex1:"l'ADISQ: Association québécoise de l'industrie du disque, du spectacle et de la video ( Québec Association for the Recording, Concert and Video Industries)",
        ex2:"",
        src: 'https://carnaval.qc.ca/en/',
        img:'./assets/images-main/facts/felix.jpg'
    },
    {
        id: 'facts6',
        name: 'Les cégeps',
        p1: "\"Les cégeps\"  is a college of general and professional studies that offers training at the pre-university and technical levels.",
        p2: "At the end of their cégep studies, which generally last 2 or 3 years depending on the program, students obtain a college diploma (DEC) which allows them either to continue their studies at university or to enter the labor market.",
        p3: "",
        ex1:"There are 48 cégeps in Quebec, of which five are in the English language.",
        ex2:"",
        src: 'https://carnaval.qc.ca/en/',
        img:'./assets/images-main/facts/cegep.jpg'
    },
    {
        id: 'facts7',
        name: 'Montreal\'s name',
        p1: "The city of Montreal takes its name from Mount Royal, the mountain in the center of the city, so named by Jacques Cartier in 1534. The city was then called Ville-Marie. At the beginning of the 18ᵉ century, the name of ville-marie was abandoned in favor of Montreal to designate the city. We recognize today that Montreal was co-founded by Jeanne Mance, a missionary, and Paul Chomedey de Maison neuve, an officer.",
        p2: "",
        p3: "",
        ex1:"",
        ex2:"",
        src: 'https://carnaval.qc.ca/en/',
        img:'./assets/images-main/facts/city.jpg'
    },
   
    {
        id: 'facts8',
        name: 'La vente-trottoir',
        p1: "Merchants often take advantage of the beautiful days of spring, summer and fall to sell their merchandise at reduced prices on the street.",
        p2: "During these special days, the street is closed to car traffic. People can shop on the street or eat street food or relax on the terraces. Sometimes there are also performances with music, dance, etc.",
        p3: "",
        ex1:"",
        ex2:"",
        src: 'https://carnaval.qc.ca/en/',
        img:'./assets/images-main/facts/street.jpg'
    },
    {
        id: 'facts9',
        name: 'Top 10 family names in Québec',
        p1: "",
        p2: "",
        p3: "",
        ex1:"",
        ex2:"",
        src: 'https://carnaval.qc.ca/en/',
        img:'./assets/images-main/facts/last.jpg'
    },
]



export const lesson1 =[
    {
        id: 'restaurant1',
        name: 'La vente-trottoir',
        p1: "This is a common greeting in a restaurant in Montreal, is a way to let you know that you can talk in French or English, and they will be able to understand you.",
        quebec1: "",
        english1: "",
        quebec2: "",
        english2: "",
        quebec3: "",
        english3: "",
        quebec4: "",
        english4: "",
        src1: './assets/audios/176.mp3',
        src2: './assets/audios/177.mp3',
        img:'./assets/images-main/lesson1/restaurant1.jpg'
    },
    {
        id: 'restaurant2',
        name: 'La vente-trottoir',
        p1: "Some restaurants are free service, and you have to order your food and take it to your table.",
        quebec1: "C'est pour ici ou pour emporter?",
        english1: "Is it for here or to go?",
        quebec2: "pour ici ",
        english2: "Means that you want to eat at the restaurant.",
        quebec3: "pour emporter",
        english3: "Means that you want to take the food to go.",
        quebec4: "",
        english4: "",
        src1: './assets/audios/176.mp3',
        src2: './assets/audios/177.mp3',
        img:'./assets/images-main/lesson1/restaurant2.jpg'
    },
    {
        id: 'restaurant3',
        name: 'La vente-trottoir',
        p1: "This is to know how many people is coming to eat with you.",
        quebec1: "C'est pour combien de personnes?",
        english1: "How many people will there be?",
        quebec2: "On va être 2 personnes, s'il vous plaît.",
        english2: "It is for two persons, please.",
        quebec3: "",
        english3: "",
        quebec4: "",
        english4: "",
        src1: './assets/audios/176.mp3',
        src2: './assets/audios/177.mp3',
        img:'./assets/images-main/lesson1/restaurant3.jpg'
    },
    {
        id: 'restaurant4',
        name: 'La vente-trottoir',
        p1: "From here you can ask wherever you want to drink, but one of the tricky options is asking just for water.",
        quebec1: "Quelque chose à boire?",
        english1: "Something to drink?",
        quebec2: "Juste de l'eau, s'il vous plaît.",
        english2: "Just water, please.",
        quebec3: "Breuvages",
        english3: "The drinks",
        quebec4: "Liqueur",
        english4: "soft drinks (coke, Pepsi, etc.)",
        src1: './assets/audios/176.mp3',
        src2: './assets/audios/177.mp3',
        img:'./assets/images-main/lesson1/restaurant4.jpg'
    },
    {
        id: 'restaurant5',
        name: 'La vente-trottoir',
        p1: "From here you can choose which ever type you want, but if you just want simple water you can say:",
        quebec1: "Plate ou pétillante?",
        english1: "Simple or sparkling?",
        quebec2: "De l'eau plate",
        english2: "Is just tap water",
        quebec3: "De l'eau pétillante",
        english3: "Is sparkling water",
        quebec4: "Juste un verre d'eau",
        english4: "Just a glass of water",
        src1: './assets/audios/176.mp3',
        src2: './assets/audios/177.mp3',
        img:'./assets/images-main/lesson1/restaurant5.jpg'
    },
    {
        id: 'restaurant6',
        name: 'La vente-trottoir',
        p1: "Merchants often take advantage of the beautiful days of spring, summer and fall to sell their merchandise at reduced prices on the street.",
        quebec1: "",
        english1: "",
        quebec2: "",
        english2: "",
        quebec3: "",
        english3: "",
        quebec4: "",
        english4: "",
        src1: './assets/audios/176.mp3',
        src2: './assets/audios/177.mp3',
        img:'./assets/images-main/lesson1/restaurant6.jpg'
    },
   
]