export const music =[
    
  {
        id: 'music1',
        name: 'Eli Rose',
        img:"./assets/images-music/elirose.jpeg",
        genre: 'Electro-pop ',
        song: 'Tôt ou tard',
        src: 'https://open.spotify.com/embed/track/4nyxfvxZhiszNKh9vBsit1?utm_source=generator',
        youtube: "https://youtu.be/eyuuZZToYdM",
    },
    {
        id: 'music2',
        name: 'Alex Nevsky',
        img:"./assets/images-music/alex.jpeg ",
        genre: 'Pop ',
        song:"Le coeur assez gros",
        src: 'https://open.spotify.com/embed/track/5H6IzDjDD4yfnYJJkd7M8k?utm_source=generator  ',
        youtube: "https://youtu.be/9thHGL2yvqQ ",
    },
    {
        id: 'music3',
        name: 'Peter Peter ',
        img:"./assets/images-music/peter.jpeg ",
        genre: 'Synth-Pop',
        song:"Noir éden",
        src: ' https://open.spotify.com/embed/track/2jZsBF0p2ZWts7ZdeAUrp6?utm_source=generator ',
        youtube: "https://youtu.be/fXDIRQLL-h8 ",
    },
    {
        id: 'music4',
        name: 'Lydia Képinski ',
        img:"./assets/images-music/lydia.jpeg ",
        genre: 'Pop ',
        song:"Premier juin",
        src: ' https://open.spotify.com/embed/track/1vnJzfR1yQXinOgFNFGdum?utm_source=generator ',
        youtube: "https://youtu.be/E859LIVka2Q ",
    },
    {
        id: 'music5',
        name: 'Xarah Dion ',
        img:"./assets/images-music/xarah.jpeg ",
        genre: 'Techno ',
        song:"Fugitive",
        src: ' https://open.spotify.com/embed/track/7Bfc3yECFj8yZvANfkjAEP?utm_source=generator ',
        youtube: "https://youtu.be/RnTDtOCCTPs ",
    },
    {
        id: 'music6',
        name: 'Coeur De Pirate ',
        img:"./assets/images-music/coeur.jpeg ",
        genre: 'Pop ',
        song:"Prémonition",
        src: ' https://open.spotify.com/embed/track/3BROl8FUuHPJ6Swvv29PFi?utm_source=generator ',
        youtube: "https://youtu.be/BgUfdhd9fzU ",
    },
    {
        id: 'music7',
        name: 'Ariane Moffat ',
        img:"./assets/images-music/ariane.jpeg ",
        genre: 'Pop ',
        song:"Pour toi",
        src: 'https://open.spotify.com/embed/track/5ZVMpcqiRYX42IIVRi0HXy?utm_source=generator  ',
        youtube: "https://youtu.be/6aRZKbtGuNw ",
    },
    {
        id: 'music8',
        name: 'FouKi ',
        img:"./assets/images-music/fouki.jpeg ",
        genre: 'Hip-Hop ',
        song:"Positif",
        src: ' https://open.spotify.com/embed/track/3vL1mbNuQ1Dw4xQ2fbPLXk?utm_source=generator ',
        youtube: "https://youtu.be/xiD40jt4aKU ",
    },
    {
        id: 'music9',
        name: 'Salomé Leclerc ',
        img:"./assets/images-music/salome.jpeg ",
        genre: 'Pop, Folk-rock ',
        song:"Tourne Encore",
        src: ' https://open.spotify.com/embed/track/1T9Wgv4cGVyoMaZc4eODtX?utm_source=generator ',
        youtube: "https://youtu.be/Vv4YkII3Hqk ",
    },
    // {
    //     id: '10',
    //     name: ' ',
    //     genre: ' ',
    //     src: '  ',
    // },
    // {
    //     id: '11',
    //     name: ' ',
    //     genre: ' ',
    //     src: '  ',
    // },
    // {
    //     id: '12',
    //     name: ' ',
    //     genre: ' ',
    //     src: '  ',
    // },
    // {
    //     id: '13',
    //     name: ' ',
    //     genre: ' ',
    //     src: '  ',
    // },
    // {
    //     id: '14 ',
    //     name: ' ',
    //     genre: ' ',
    //     src: '  ',
    // },
    // {
    //     id: ' 15',
    //     name: ' ',
    //     genre: ' ',
    //     src: '  ',
    // },
    // {
    //     id: '16 ',
    //     name: ' ',
    //     genre: ' ',
    //     src: '  ',
    // },

]

// {
//     id: ' ',
//     name: ' ',
//     genre: ' ',
//     song: ' ',
//     src: '  ',
// },