export const entriesWords =[
    
    {
        id: '1',
        quebec: 'Achaler',
        french: 'Ennuyer/importuner ',
        english: 'Annoy',
        frenchMeaning: 'Ce verbe provient probablement du verbe "chaloir" qui voulait dire "importuner de façon excessive" en vieux dialecte normand.',
        englishMeaning: 'This verb probably comes from the verb "chaloir" which meant "to bother excessively" in the old Norman dialect.',
        exampleFrench: 'Papa, arrête de m\'achaler.',
        exampleEnglish: 'Daddy, stop bugging me.',
        src: './assets/images/achaler.jpg ',
    },
    {
        id: '2',
        quebec: ' Une babiche ',
        french: ' Une raquette à neige ',
        english: 'A snowshoe ',
        frenchMeaning: 'Ce mot provient du terme algonquien "ababich" qui signifie corde et correspond à un type de corde traditionnelle fabriquée par les peuples autochtones amérindiens à partir de lanières de cuir de wapiti ou de cerf.',
        englishMeaning: 'This word comes from the Algonquian term "ababich" which means rope and corresponds to a type of traditional rope made by Native American Indian peoples from elk or deer leather thongs.',
        src: './assets/images/babiche.jpg',
    },
    {
        id: '3',
        quebec: 'Une binne',
        french: 'Un haricot ',
        english: ' Bean ',
        frenchMeaning: ' Ce mot québécois est un anglicisme qui provient directement du mot anglais "bean". ',
        englishMeaning: ' This Quebec word is an Anglicism which comes directly from the English word "bean"  ',
        src: ' ./assets/images/binne.jpg',
    },
    {
        id: '4',
        quebec: 'Bienvenue ',
        french: 'De rien/avec plaisir/pas de quoi ',
        english: ' You\'re welcome ',
        frenchMeaning: ' Ce mot provient directement de la traduction française de l\'expression "You are welcome" utilisée par les anglophones dans ce contexte spécifique. ',
        englishMeaning: 'This word comes directly from the French translation of the expression "You are welcome" used by English speakers in this specific context.   ',
        src: ' ./assets/images/bienvenue.jpg ',
    },
    {
        id: '5',
        quebec: 'Les bobettes ',
        french: 'Une culotte, un slip (bref, un sous-vêtement) ',
        english: ' Panties, underwear  ',
        frenchMeaning: 'L\'origine de ce mot québécois est très mystérieux. L\'hypothèse la plus vraisemblable est qu\'il viendrait du verbe anglais "to bob" qui signifie "danser, s\'agiter, se balancer", auquel les Québécois auraient ajouter le suffixe "ette" pour créer ce mot.  ',
        englishMeaning: ' The origin of this Quebec word is very mysterious. The most likely hypothesis is that it would come from the English verb "to bob" which means "to dance, to agitate, to swing", to which Quebecers would have added the suffix "ette" to create this word.  ',
        src: ' ./assets/images/bobettes.jpg',
    },

    {
        id: '6',
        quebec: 'La boîte à malle ',
        french: 'La boîte aux lettres ',
        english: 'The mailbox ',
        frenchMeaning: 'Ce mot provient d\'une traduction littérale puis fancisée du mot anglais "mailbox". Le mot "mail" s\'étant petit à petit transformé en "malle" avec la parlure québécoise.  ',
        englishMeaning: ' This word comes from a literal and then fancized translation of the English word "mailbox". The word "mail" having gradually transformed into a "malle" with the Quebec parlance.  ',
        src: './assets/images/mailbox.jpg ',
    },
    {
        id: '7',
        quebec: 'La boucane',
        french: ' La fumée ',
        english: ' Smoke ',
        frenchMeaning: 'Ce mot vient du verbe "boucaner" qui signifie exposer de la viande ou du poisson à la fumée pour les conserver en les faisant sécher.  ',
        englishMeaning: ' This word comes from the verb "boucaner" which means to expose meat or fish to smoke in order to preserve them by drying them. ',
        src: './assets/images/boucane.jpeg',
    },
    {
        id: '8',
        quebec: 'Un caribou',
        french: ' Un renne ',
        english: ' A reindeer ',
        frenchMeaning: ' "Caribou" viendrait du mot indien "xalibu", qui signifie "celui qui se sert de ses sabots comme d\'une pelle". En effet, le caribou gratte la neige avec ses pattes pour trouver de la nourriture dessous. ',
        englishMeaning: '"Caribou" would come from the Indian word "xalibu", which means "the one who uses his hooves as a shovel". Indeed, the caribou scratch the snow with its paws to find food underneath.  ',
        src: './assets/images/caribou.jpg  ',
    },
    {
        id: '9',
        quebec: ' Un char',
        french: ' Une voiture',
        english: ' A car ',
        frenchMeaning: 'Contrairement à ce que l\'on pourrait croire, ce terme ne provient pas de l\'anglais "car" mais fait référence à une voiture romaine à deux roues attelée à des chevaux, de la même racine que "charrue", "chariot" ou encore "charrette".',
        englishMeaning: 'Contrary to what one might think, this term does not come from the English "car" but refers to a Roman car with two wheels hitched to horses, from the same root as "plow", "chariot" or still "cart". ',
        src: './assets/images/char.jpg ',
    },
    {
        id: '10',
        quebec: 'Le champlure',
        french: 'Un robinet ',
        english: 'A tap  ',
        frenchMeaning: ' Ce mot québécois vient certainement du mot "chantepleure" qui était une sorte d’entonnoir avec un long tuyau percé de trous pour faire couler les liquides dans un tonneau ou une cuve. ',
        englishMeaning: '  This Quebec word certainly comes from the word "chantepleure" which was a sort of funnel with a long pipe pierced with holes to allow liquids to flow into a barrel or tank.',
        src: './assets/images/champlure.jpg ',
    },
    {
        id: '11',
        quebec: ' Un chaudron',
        french: ' Une casserole ou une marmite ',
        english: ' A saucepan or a pot ',
        frenchMeaning: ' Les Québécois continuent à utiliser ce mot pour parler d\'un récipient dans lequel on fait chauffer de l\'eau ou un aliment. ',
        englishMeaning: 'Quebeckers continue to use this word to refer to a container in which water or food is heated.  ',
        src: ' ./assets/images/chaudron.jpg',
    },
    {
        id: '12',
        quebec: ' Un chien-chaud ',
        french: 'Un hot dog ',
        english: ' A hot dog ',
        frenchMeaning: 'Une traduction littérale de cet aliment typiquement nord-américain.  ',
        englishMeaning: 'A literal translation of this uniquely North American food.  ',
        src: ' ./assets/images/chienchaud.jpg ',
    },
    {
        id: '13',
        quebec: 'Un chum',
        french: ' Un pote, un mec',
        english: 'A friend, a guy  ',
        frenchMeaning: ' Ce terme est un anglicisme qui vient du même mot anglais "chum". ',
        englishMeaning: 'This term is an Anglicism which comes from the same English word "chum".  ',
        src: ' ./assets/images/chum.jpg',
    },
    {
        id: '14',
        quebec: ' Un clavardage',
        french: 'Un chat (sur internet) ',
        english: ' A chat (on the internet) ',
        frenchMeaning: 'Ce terme est un mot-valise d\'origine purement québecoise composé des mots "clavier" et "bavardage".  ',
        englishMeaning: ' This term is a word purely from Quebec composed of the words "keyboard" and "chatter". ',
        src: './assets/images/clavardage.jpg  ',
    },
    {
        id: '15',
        quebec: 'Un cotteur',
        french: ' Un trottoir ',
        english: 'A sidewalk  ',
        frenchMeaning: 'Ce terme désigne la bande de béton d\'environ 10 cm de large bordant les rues donc "à côté" de la route.  ',
        englishMeaning: ' This term refers to the approximately 10 cm wide concrete strip bordering the streets and therefore "next to" the road. ',
        src: ' ./assets/images/cotteur.jpg ',
    },
    {
        id: '16',
        quebec: ' Une débarbouillette',
        french: 'Un gant (de toilette)',
        english: ' Wash cloths',
        frenchMeaning: 'Ce mot provient du verbe "débarbouiller".  ',
        englishMeaning: ' This word comes from the verb "to wash off". ',
        src: './assets/images/wash.jpg ',
    },
    {
        id: '17',
        quebec: ' Le dépanneur',
        french: 'L\'épicerie du coin ',
        english: ' The local grocery store ',
        frenchMeaning: 'Ce terme est utilisé pour parler d\'un petit magasin offrant toute sorte d\'articles de nécessité et ouvert plus tard que les autres. Il peut donc "dépanner" tout au long de la journée.  ',
        englishMeaning: 'This term is used to refer to a small store offering all kinds of necessities and open later than others. He can therefore "dépanner" throughout the day.  ',
        src: ' ./assets/images/depanneur.jpg ',
    },
    {
        id: '18',
        quebec: 'Des espadrilles',
        french: 'Des tennis, des baskets ',
        english: 'Sneakers ',
        frenchMeaning: ' Ce terme provient d\'une confusion avec les premières chaussures de tennis en toile. ',
        englishMeaning: 'This term originates from a confusion with the first canvas tennis shoes.  ',
        src: ' ./assets/images/tennis.jpg ',
    },
    {
        id: '19',
        quebec: 'La facture',
        french: ' L\'addition (au restaurant) ou le reçu (achat) ',
        english: 'The bill (at the restaurant) or the receipt (purchase) ',
        frenchMeaning: ' Au-delà de la signification ordinaire, les Québécois utilisent ce mot pour tout document qui indique un prix (service, marchandise, etc). ',
        englishMeaning: 'Beyond the ordinary meaning, Quebecers use this word for any document that indicates a price (service, merchandise, etc.).  ',
        src: './assets/images/facture.jpg  ',
    },
    {
        id: '20',
        quebec: 'Fortiller',
        french: 'Gigoter ',
        english: '  ',
        frenchMeaning: 'Ce mot serait le résultat d\'un croisement entre les verbes frétiller et tortiller.  ',
        englishMeaning: ' This word would be the result of a cross between the verbs wriggle and squirm. ',
        src: ' ./assets/images/fortiller.jpg ',
    },
    // {
    //     id: '21',
    //     quebec: 'les foufounes',
    //     french: 'les fesses ',
    //     english: ' buttocks ',
    //     frenchMeaning: 'Un faux ami qui peut entraîner des quiproquos très embarassants !  ',
    //     englishMeaning: ' A false friend who can lead to very embarrassing misunderstandings! ',
    //     src: '  ',
    // },
    {
        id: '22',
        quebec: 'frencher',
        french: 'rouler une pelle ',
        english: ' snog ',
        frenchMeaning: ' Ce verbe provient du verbe anglais "to french kiss". ',
        englishMeaning: ' This verb comes from the English verb "to french kiss". ',
        src: ' ./assets/images/frencher.jpg',
    },
    {
        id: '23',
        quebec: 'frette',
        french: ' très froid (moins 20°C et au-dessous) ',
        english: ' very cold (minus 20 ° C and below) ',
        frenchMeaning: ' L\'origine de ce mot est probablement le vieux français "freid", qui est ensuite devenu "froid". Il se réfère généralement à la température extérieure. ',
        englishMeaning: ' The origin of this word is probably the old French "freid", which later became "cold". It generally refers to the outside temperature. ',
        src: './assets/images/frette.jpg  ',
    },
    {
        id: '24',
        quebec: 'gazer',
        french: 'mettre de l\'essence ',
        english: 'Refuel  ',
        frenchMeaning: 'Ce verbe est la version francisée du verbe anglo-américain "to gas up" qui signifie faire le plein d\'essence. Verbe provenant lui-même du mot \'gas\' que les Américains utilisent pour "essence".  ',
        englishMeaning: ' This verb is the French version of the Anglo-American verb "to gas up" which means to fill up with gasoline. Verb itself derived from the word \'gas\' that Americans use for "gasoline". ',
        src: './assets/images/gazer.jpg  ',
    },
    {
        id: '25',
        quebec: 'les gosses ',
        french: 'les couilles ',
        english: ' the balls ',
        frenchMeaning: 'vulgaire, synonyme de testicule. Utiliser comme verbe, comme dans tu me gosses, il signifieque tu m\'énerves.  ',
        englishMeaning: 'Vulgar, synonyms of the testicle. To use as a verb, it means that you annoy me.',
        src: ' ./assets/images/gosses.jpg ',
    },
    {
        id: '26',
        quebec: 'un ivressomètre ',
        french: 'un éthylotest ou éthylomètre ',
        english: ' a breathalyzer ',
        frenchMeaning: 'L\'éthylotest mesure le taux d\'éthanol (ou alcool éthylique) dans le sang. Bref, il mesure si une personne est en état d\'ivresse. Pourquoi se compliquer la vie ?!  ',
        englishMeaning: 'The breathalyzer measures the level of ethanol (or ethyl alcohol) in the blood. In short, it measures whether a person is drunk.  ',
        src: ' ./assets/images/alcohol.jpg ',
    },
    {
        id: '27',
        quebec: 'une jambette',
        french: 'un croc-en-jambe, un croche-pied, un croche-patte ',
        english: ' a tripod ',
        frenchMeaning: 'La jambette est un terme souvent relatif au sport pour parler d\'un jeu de "jambes" destiné à déstabiliser l\'adversaire.  ',
        englishMeaning: ' The jambette is a term often relating to sport to speak of a game of "legs" intended to destabilize the opponent. ',
        src: ' ./assets/images/jambette.jpg',
    },
    {
        id: '28',
        quebec: 'une laveuse',
        french: 'un lave-linge ',
        english: ' a washing machine ',
        frenchMeaning: ' Ce terme est une traduction directe du mot anglais "washer". ',
        englishMeaning: ' This term is a direct translation of the English word "washer" ',
        src: ' ./assets/images/laveuse.jpg ',
    },
    {
        id: '29',
        quebec: 'un linge',
        french: 'une serpière, un chiffon, linge de maison ',
        english: ' a mop, a cloth, household linen ',
        frenchMeaning: 'Pour les Québécois, le terme "linge" sert plutôt à parler de tissus utilisés pour la maison.  ',
        englishMeaning: 'For Quebecers, the term "linen" is more used to talk about fabrics used for the home.  ',
        src: ' ./assets/images/linge.jpg ',
    },
    {
        id: '30',
        quebec: 'une liqueur',
        french: ' un soda ',
        english: 'a soda  ',
        frenchMeaning: ' des boissons gazeuses sucrées.',
        englishMeaning: 'sugary soft drinks.  ',
        src: './assets/images/liqueur.jpg ',
    },
    {
        id: '31',
        quebec: 'le magasinage ',
        french: ' le shopping ',
        english: ' shopping ',
        frenchMeaning: ' Ce terme provient du substantif "magasin" et il est construit de la même façon que le mot anglais "shopping" sur la base du verbe "to shop". ',
        englishMeaning: ' This term comes from the noun "store" and it is constructed in the same way as the English word "shopping" on the basis of the verb "to shop". ',
        src: ' ./assets/images/magasinage.jpg ',
    },
    {
        id: '32',
        quebec: 'un maringuouin',
        french: 'un moustique ',
        english: 'a mosquito ',
        frenchMeaning: 'Les colons français ont emprunté le terme "maringuouin" à la langue tupi, d\'un peuple indigène du Brésil, au 16ème siècle. Il est toujours utilisé par les Québécois même si le mot "moustique" gagne du terrain.  ',
        englishMeaning: ' French settlers borrowed the term "maringuouin" from the Tupi language, from an indigenous people of Brazil, in the 16th century. It is still used by Quebecers even if the word "mosquito" is gaining ground. ',
        src: './assets/images/maringuouin.jpg ',
    },
    {
        id: '33',
        quebec: 'une pinotte',
        french: 'une cacahuète ',
        english: 'a peanut',
        frenchMeaning: ' Ce mot provient directement du mot anglais "peanut". Comme en anglais et en français, le mot "pinotte" au pluriel signifie de faible valeur. ',
        englishMeaning: ' This word comes directly from the English word "peanut". As in English and French, the word "pinotte" in the plural means low value. ',
        src: ' ./assets/images/pinotte.jpg ',
    },
    {
        id: '34',
        quebec: 'un robeur',
        french: 'un pneu',
        english: ' a tire ',
        frenchMeaning: 'Ce terme est un anglicisme provenant du mot anglais "rubber" qui signifie "caoutchouc".  ',
        englishMeaning: ' This term is an Anglicism coming from the English word "rubber" which means "caoutchouc". ',
        src: './assets/images/robeur.jpg  ',
    },
    {
        id: '35',
        quebec: 'un siffleux',
        french: 'une marmotte ',
        english: 'a marmot  ',
        frenchMeaning: 'Puisque les marmottent sifflent pour prévenir la colonie d\'un danger.  ',
        englishMeaning: 'Since groundhogs hiss to warn the colony of danger.  ',
        src: './assets/images/marmot.jpg',
    },
    {
        id: '36',
        quebec: 'tabarnak',
        french: 'équivalent de putain ',
        english: ' fucking ',
        frenchMeaning: '"Tabarnak" est la contraction du mot "tabernacle". Comme la plupart des jurons québécois, il est blasphématoire. On l\'utilise comme le mot "putain" en français de France. Il exprime donc des sentiments forts comme la frustration, la colère, l\'énervement ou même la surprise.  ',
        englishMeaning: ' "Tabarnak" is the contraction of the word "tabernacle". Like most Quebec swear words, it is blasphemous. It is used as the word "whore" in French from France. He therefore expresses strong feelings such as frustration, anger, nervousness or even surprise. ',
        src: ' ./assets/images/tabarnak.jpg ',
    },
    {
        id: '37',
        quebec: 'tiguidou',
        french: 'génial, super, trop bien ',
        english: 'awesome, great, too good  ',
        frenchMeaning: ' Ce terme est une pure création québécoise à l\'origine obscure. La théorie la plus plausible est celle d\'une variante de l\'expression écossaise "tickety-boo" qui signifie "aller lentement, mais sûrement". ',
        englishMeaning: ' This term is a pure Quebec creation of obscure origin. The most plausible theory is that of a variation of the Scottish expression "tickety-boo" which means "to go slowly, but surely". ',
        src: ' ./assets/images/tiguidou.jpg ',
    },
    {
        id: '38',
        quebec: 'les vidanges ',
        french: 'les déchets/ordures/poubelles ',
        english: ' waste / garbage / bins',
        frenchMeaning: 'Si l\'on vous demande de sortir les vidanges, on ne parle pas de votre voiture ! ',
        englishMeaning: ' If you are asked to take out "les vidanges", we are not talking about your car!',
        src: './assets/images/vidanges.jpg  ',
    }
    // {
    //     id: '38',
    //     quebec: '',
    //     french: ' ',
    //     english: ' ',
    //     frenchMeaning: ' ',
    //     englishMeaning: ' ',
    //     src: '  ',
    // }
]