export const entriesExpressions =[
    
    {
        id: '1',
        quebec: 'Attendre que le curé se mouche',
        french: ' être patient, attendre le bon moment pour faire quelque chose. ',
        english: 'Be patient, wait for the right time to do something. ',
        example:'"Ugh, mon chum c\'est en retard encore il toujours attendre que le curé se mouche" ',
        src: "./assets/audios/p1.mp3"  ,
        img:"./assets/images-expressions/p1.webp"
    },
    {
        id: '2',
        quebec: 'Avoir de l\'eau dans la cave ',
        french: 'Porter des pantalons trop courts (« cave » signifie « sous-sol » dans ce contexte). ',
        english: ' Wearing pants that are too short ("cave" means "basement" in this context). ',
        example:'" Regarde ton fils, il a de l’eau dans la cave, il ferait mieux d’aller magasiner !" ',
        src: './assets/audios/p2.mp3 ',
        img:"./assets/images-expressions/p2.webp"
    },
    {
        id: '3',
        quebec: 'Avoir de la broue dans le toupet',
        french: ' Être débordé, manquer de temps, être très pressé, être excité, être agité',
        english: 'Being overwhelmed, running out of time, being in a big rush, being excited, being restless ',
        example:'"J’ai tellement de travaille à faire. Je crois que je vais avoir besoin d’aide, j’ai la broue dans le toupet." ',
        src: ' ./assets/audios/p3.mp3',
        img:"./assets/images-expressions/p3.webp"
        
    },
    {
        id: '4',
        quebec: 'Avoir la fly à l\'air ',
        french: 'Avoir la braguette ouverte. ',
        english: ' Have your fly open. ',
        example:' " Bob le savait pas, mais il avait la fly à l\'air tout le long de son exposé!"',
        src: ' ./assets/audios/p4.mp3',
        img:"./assets/images-expressions/p4.webp"
    },
    {
        id: '5',
        quebec: 'Avoir du front tout le tour de la tête.',
        french: ' Être effronté, avoir de l’aplomb, de l’audace, du toupet. ',
        english: 'To be cheeky, to have poise, daring, nerve. ',
        example:'"Ben? Tu aurais dû le voir aller à La Porte Rouge. Il plottait tout ce qui bougeait. Il a vraiment du front tout le tour de la tête. C\'est mon héros." ',
        src: ' ./assets/audios/p5.mp3',
        img:"./assets/images-expressions/p5.webp"
    },
    {
        id: '6',
        quebec: 'Avoir de la mine dans le crayon. ',
        french: 'Avoir une forte libido. ',
        english: 'Have a strong libido. ',
        example:'"Elle m’en a fait baver la rousse, au lit on partait facilement pour la gloire, j’ai de la mine dans le crayon, je lui en ai fait baver aussi, à l’époque je ne me contrôlais pas toujours, […]." ',
        src: ' ./assets/audios/p6.mp3',
        img:"./assets/images-expressions/p6.webp"
    },
    {
        id: '7',
        quebec: 'Chiquer la guenille',
        french: 'Une drôle d’expression québécoise qui qualifie une personne qui ronchonne.  ',
        english: 'A funny Quebec expression that qualifies a person who grieves. ', 
        example:'"Ma voisine passe son temps à chiquer la guenille." ',
        src: ' ./assets/audios/p7.mp3',
        img:"./assets/images-expressions/p7.webp"
    },
    {
        id: '8',
        quebec: 'Avoir un pain au four',
        french: ' Veut dire «être enceinte», c’est une manière bien poétique de parler de grossesse.',
        english: 'Means "to be pregnant", it\'s a very poetic way of talking about pregnancy. ',
        example:'"Elle a un pain dans le four et pas d\'homme." ',
        src: ' ./assets/audios/p8.mp3',
        img:"./assets/images-expressions/p8.webp"
    },
    {
        id: '9',
        quebec: 'Avoir son voyage ',
        french: 'Ne plus être capable d’endurer. ',
        english: 'No longer being able to endure. ',
        example:'"J’ai passé seize heures à attendre à l’aéroport. Je commençais sérieusement à avoir mon voyage." ',
        src: ' ./assets/audios/p9.mp3',
        img:"./assets/images-expressions/p9.webp"
       
    },
    {
        id: '10',
        quebec: 'Avoir les yeux dans la graisse de binnes',
        french: ' Quand on ne voit d\'une personne ou d\'une bête que le blanc de ses yeux, sans pupilles visibles. ',
        english: 'When all we see of a person or an animal is the whites of their eyes, without visible pupils. ',
        example:'"Le cuistot, épuisé par le manque de sommeil, avait les yeux dans la graisse de bines devant ses fourneaux." ',
        src: ' ./assets/audios/p10.mp3',
        img:"./assets/images-expressions/p10.webp"
    },
    {
        id: '11',
        quebec: 'Baiser le cul du diable quand il est frette',
        french: 'Faire quelque chose en temps et en heure. ',
        english: 'Do something on time. ',
        example:' "baiser le cul du diable quand il est frette"',
        src: ' ./assets/audios/p11.mp3',
        img:"./assets/images-expressions/p11.webp"
     },
    {
        id: '12',
        quebec: 'Ça vient de s\'éteindre',
        french: ' Il n\'y a plus d\'espoir.',
        english: 'There is no hope. ',
        example:'"Avec le but que vient d\'accorder Carey Price, ça vient de s\'éteindre pour le CH!" ',
        src: ' ./assets/audios/p12.mp3',
        img:"./assets/images-expressions/p12.webp"
    },
    {
        id: '13',
        quebec: 'Caller l\'orignal ',
        french: 'Vomir (bruyamment) après une soirée bien arrosée. Du verbe anglais « to call », appeler – il semblerait que les chasseurs québécois aient eu pour habitude d’attirer l’orignal en imitant son cri lorsqu’il est en rut.',
        english: ' Vomiting (loudly) after a drunken night. From the English verb "to call", to call - it seems that Quebec hunters used to attract moose by imitating its call when in heat.',
        example:'"Louis ? Il est en train de caller l’orignal." ',
        src: ' ./assets/audios/p13.mp3',
        img:"./assets/images-expressions/p13.webp"
    },
    {
        id: '14',
        quebec: 'Se calmer le pompon ',
        french: 'Cesser d\'être exagérément enthousiaste, scandalisé ou paniqué devant une idée ou une situation. ',
        english: 'Stop being overly enthusiastic, scandalized or panicked by an idea or a situation. ',
        example:'"Calme-toi le pompon, tu vois bien qu’on n’y est pour rien !" ',
        src: ' ./assets/audios/p14.mp3',
        img:"./assets/images-expressions/p14.webp"
    },
    {
        id: '15',
        quebec: 'Cogner des clous',
        french: 'Lutter tant bien que mal contre le sommeil. ',
        english: 'Fight as best you can against sleep. ',
        example:'" Michel cognait des clous devant la télé." ',
        src: ' ./assets/audios/p15.mp3',
        img:"./assets/images-expressions/p15.webp"
    },
    {
        id: '16',
        quebec: 'Courir la galipote',
        french: 'Aller à l\'aventure. ',
        english: 'Go on an adventure. ',
        example:'"Hey, Gérard tu viens avec moi courir la galipote?" ',
        src: ' ./assets/audios/p16.mp3',
        img:"./assets/images-expressions/p16.webp"
    },
    {
        id: '17',
        quebec: 'Donner son 4% à quelqu\'un',
        french: ' Congédier quelqu’un, ou lui signifier qu’il le sera bientôt ',
        english: 'Fire someone, or let them know they will be soon ',
        example:'" J\'y ai donné son 4%, merci, bonsoir!" ',
        src: ' ./assets/audios/p17.mp3',
        img:"./assets/images-expressions/p17.webp"
    },
    {
        id: '18',
        quebec: 'Être vite sur ses patins',
        french: 'Rapide, capable de s’adapter rapidement. ',
        english: 'Fast, able to adapt quickly. ',
        example:'"Il est vite sur ses patins!" ',
        src: ' ./assets/audios/p18.mp3',
        img:"./assets/images-expressions/p18.webp"
    },
    {
        id: '19',
        quebec: 'Faire du pouce',
        french: ' Arrêter un véhicule dans le but de se faire transporter gratuitement.',
        english: 'Stop a vehicle for the purpose of being transported free of charge. ',
        example:'"Le routard fait du pouce." ',
        src: ' ./assets/audios/p19.mp3',
        img:"./assets/images-expressions/p19.webp"
    },
    {
        id: '20',
        quebec: 'Faire du train',
        french: 'Faire du bruit, du tapage. On l’utilise entre autres pour faire référence à une agitation bruyante, un tumulte collectif. ',
        english: 'Make noise, noise. It is used, among other things, to refer to a noisy agitation, a collective uproar. ',
        example:'" Je vous apprendrai, tas dé canaille, à faire du train " ',
        src: ' ./assets/audios/p20.mp3',
        img:"./assets/images-expressions/p20.webp"
    },
    {
        id: '21',
        quebec: 'Se faire prendre pour une valise',
        french: 'Passer pour un imbécile. ',
        english: 'Sound like a fool. ',
        example:'"Tu crois que je te crois ? Coudonc, me prends-tu pour une valise ?" ',
        src: ' ./assets/audios/p21.mp3',
        img:"./assets/images-expressions/p21.webp"
    },
    {
        id: '22',
        quebec: 'Se fendre le cul',
        french: 'Faire un effort de manière soutenue, tout essayer ',
        english: 'Make a sustained effort, try everything ',
        example:'"Je me suis fendu le cul pour t\'envoyer à l\'école privée pis toi tu t\'inscris en phisolophie!" ',
        src: ' ./assets/audios/p22.mp3',
        img:"./assets/images-expressions/p22.webp"
    },
    {
        id: '23',
        quebec: 'Niaiser avec la puck',
        french: 'Hésiter avant de prendre une décision, craindre de foncer, procéder de façon hésitante. ',
        english: 'Hesitant before making a decision, fear of forging ahead, hesitantly proceeding ',
        example:'"Niaise pas avec la puck" ',
        src: ' ./assets/audios/p23.mp3',
        img:"./assets/images-expressions/p23.png"
    },
    {
        id: '24',
        quebec: 'lâche pas la patate',
        french: ' Ne pas abandonner.',
        english: ' Dont give up.',
        example:'"Enwouaille, t\'as presque fini, lâche pas la patate!" ',
        src: ' ./assets/audios/p24.mp3',
        img:"./assets/images-expressions/p24.jpeg"
    },
    {
        id: '25',
        quebec: 'Se paqueter la fraise ',
        french: 'Boire ou manger avec excès',
        english: 'Drinking or eating to excess ',
        example:' "J’ai hâte de me paqueter la fraise durant mon prochain voyage au Mexique."',
        src: ' ./assets/audios/p25.mp3',
        img:"./assets/images-expressions/p25.webp"
    },
    {
        id: '26',
        quebec: 'Parler à travers son chapeau',
        french: 'Parler d’une chose que l’on connait à peine ou pas du tout. ',
        english: 'Talk about something you hardly know or don\'t know at all. ',
        example:'"Cet homme parlait de physique quantique alors qu’il est vendeur d’automobiles, il parle à travers son chapeau." ',
        src: ' ./assets/audios/p26.mp3',
        img:"./assets/images-expressions/p26.webp"
        },
    {
        id: '27',
        quebec: 'Passer la nuit sur la corde à linge',
        french: 'Passer une mauvaise nuit et/ou ne pas dormir beaucoup. ',
        english: 'Having a bad night and / or not getting much sleep. ',
        example:' "Tu n’as pas bonne mine – J’ai passé la nuit sur la corde à linge."',
        src: ' ./assets/audios/p27.mp3',
        img:"./assets/images-expressions/p27.jpeg"
        
    },
    {
        id: '28',
        quebec: 'Péter au frette ',
        french: 'Se briser, cesser de fonctionner à cause du froid. ',
        english: 'To break, to stop working because of the cold. ',
        example:'"Ma pompe a pété au frette." ',
        src: ' ./assets/audios/p28.mp3',
        img:"./assets/images-expressions/p28.webp"
        },
    {
        id: '29',
        quebec: 'Péter de la broue',
        french: ' Faire de l’esbroufe, se vanter, essayer d’en imposer. ',
        english: 'Show off, brag, try to impose. ',
        example:'"Arrête donc de péter de la broue !" ',
        src: ' ./assets/audios/p29.mp3',
        img:"./assets/images-expressions/p29.webp"
    },
    {
        id: '30',
        quebec: 'Se pogner le bacon',
        french: ' Ne rien faire ou perdre son temps. ',
        english: 'Do nothing or waste your time. ',
        example:' ',
        src: ' ./assets/audios/p30.mp3',
        img:"./assets/images-expressions/p30.webp"
    },
    {
        id: '31',
        quebec: 'Tomber en amour',
        french: 'Tomber amoureux ; devenir amoureux. ',
        english: 'To fall in love ; to become in love. ',
        example:'"Or, comme l’amour est une maladie, on doit dire tomber amoureux, & tomber en amour, comme tomber en apoplexie." ',
        src: ' ./assets/audios/p31.mp3',
        img:"./assets/images-expressions/p31.webp"
    },
    {
        id: '32',
        quebec: 'Tomber des peaux de lièvre ',
        french: 'Gros flocons de neige.',
        english: ' Big snowflakes.',
        example:'" Neiger en peau de lièvre (Québec) : neiger à gros flocons." ',
        src: ' ./assets/audios/p32.mp3',
        img:"./assets/images-expressions/p32.jpeg"
    },
    {
        id: '33',
        quebec: 'Être assis sur son steak',
        french: ' S’utilise pour désigner une personne qui ne fait rien, qui se tourne les pouces. ',
        english: 'Used to denote a person who does nothing, who twiddles his thumbs. ',
        example:'" Merci pour ton aide, j’ai préparé le dîner pendant que tu étais assis sur ton steak." ',
        src: ' ./assets/audios/p33.mp3',
        img:"./assets/images-expressions/p33.webp"
    },
    {
        id: '34',
        quebec: 'Sentir le swing',
        french: 'Sentir la transpiration. ',
        english: 'smell of perspiration. ',
        example:'"Chéri tu sens le swing, tu voudrais pas aller prendre une douche ?" ',
        src: ' ./assets/audios/p34.mp3',
        img:"./assets/images-expressions/p34.webp"
    },
    {
        id: '35',
        quebec: 'Se sécher les dents ',
        french: 'Se dit de quelqu’un qui sourit de manière forcée. Désigne par extension un comportement faux-cul ',
        english: 'Said of someone who is forced to smile. Designates by extension a false-ass behavior ', 
        example:'"T’as pas un peu fini de te sécher les dents devant le patron ?" ',
        src: ' ./assets/audios/p35.mp3',
        img:"./assets/images-expressions/p35.webp"
    },
    {
        id: '36',
        quebec: 'Tirer une bûche',
        french: 'S’utilise pour inviter quelqu’un à s’asseoir. Date d’une lointaine époque à laquelle les gens avaient peu de moyens et des bûches en guise de siège. ',
        english: 'Use to invite someone to sit down. Date from a distant time when people had little means and logs for siege. ', 
        example:'" Allez, Roger, tire-toi une bûche !" ',
        src: ' ./assets/audios/p36.mp3',
        img:"./assets/images-expressions/p36.png"
    },
    {
        id: '37',
        quebec: 'Toutter de la haine',
        french: 'Cette expression québécoise est synonyme de klaxonner. ',
        english: ' This Quebec expression is synonymous with honking.', 
        example:'"Il doit y avoir un embouteillage, ils sont tous en train de toutter de la haine." ',
        src: ' ./assets/audios/p37.mp3',
        img:"./assets/images-expressions/p37.webp"
    },
    {
        id: '38',
        quebec: 'Accrocher ses patins',
        french: 'Abandonner, jeter l’éponge. ',
        english: 'Give up, throw in the towel. ', 
        example:'" Il a tenté le concours du plus gros mangeur de poutine mais il a dû accrocher ses patins." ',
        src: ' ./assets/audios/p38.mp3',
        img:"./assets/images-expressions/p38.jpeg"
    },
    {
        id: '39',
        quebec: 'Attacher sa tuque',
        french: 'Au Québec, une tuque est un bonnet. Cette expression québécoise signifie donc « s’accrocher », « se tenir prêt ».  ',
        english: 'In Quebec, a tuque is a cap. This Quebec expression therefore means "to hang on", "to be ready". ', 
        example:'"Attache ta tuque, ça va décoiffer ! "',
        src: ' ./assets/audios/p39.mp3',
        img:"./assets/images-expressions/p39.jpeg"
    },
    {
        id: '40',
        quebec: 'Avoir eu des coups de pied dans l’cul ',
        french: 'Se dit de quelqu’un de très grand. ',
        english: 'Said to himself of someone very tall. ', 
        example:'" Quel échalas celui-là, il a eu des coups de pied dans l’cul !" ',
        src: ' ./assets/audios/p40.mp3',
        img:"./assets/images-expressions/p40.webp"
    },
    {
        id: '41',
        quebec: 'Avoir l’air d’la chienne à Jacques ',
        french: 'Se dit de quelqu’un de mal habillé. ',
        english: 'someone badly dressed. ', 
        example: '" Non mais regarde comment tu es accoutré, tu as l’air de la chienne à Jacques !"',
        src: ' ./assets/audios/p41.mp3',
        img:"./assets/images-expressions/p41.webp"
    },
    {
        id: '42',
        quebec: 'Avoir les mains pleines de pouces',
        french: 'Être maladroit, avoir deux mains gauches. Une expression québécoise qui parle d’elle-même ! ',
        english: 'To be clumsy, to have two left hands. A Quebec expression that speaks for itself! ', 
        example:'"Clémentine est une catastrophe, elle a les mains pleines de pouces." ',
        src: ' ./assets/audios/p42.mp3',
        img:"./assets/images-expressions/p42.webp"
    },
    {
        id: "43",
        quebec: "Avoir la chienne",
        french: " Avoir peur",
        english: "To fear",
        src:'./assets/audios/43.mp3 ',
    },
      {
        id: "44",
        quebec: "Avoir la danse de St-Guy",
        french: " Bouger tout le temps",
        english: "Move all the time",
        src:'./assets/audios/44.mp3 ',
    },
      {
        id: "45",
        quebec: "Arrête de chialer",
        french: " Arrête de te plaindre",
        english: "Stop complaining",
        src:'./assets/audios/45.mp3 ',
    },
      {
        id: "46",
        quebec: "Avoir la falle basse",
        french: " Avoir l’air triste",
        english: "look sad",
        src:'./assets/audios/46.mp3 ',
    },
      {
        id: "47",
        quebec: "Avoir la guédille au nez",
        french: " Avoir la goutte au nez ou le nez qui coule",
        english: " Having a runny or runny nose",
        src:'./assets/audios/47.mp3 ',
    },
      {
        id: "48",
        quebec: "Avoir la gueule fendue jusqu’au oreilles",
        french: " Sourire largement",
        english: "smile broadly",
        src:'./assets/audios/48.mp3 ',
    },
      {
        id: "49",
        quebec: "Avoir le flu",
        french: " Avoir la diarrhée",
        english: "have diarrhea",
        src:'./assets/audios/49.mp3 ',
    },
      {
        id: "50",
        quebec: "Avoir les baguettes en l’air",
        french: " S’énerver",
        english: " get angry",
        src:'./assets/audios/50.mp3 ',
    },
      {
        id: "51",
        quebec: "Avoir les bleus",
        french: " Etre triste, mélancolique",
        english: "To be sad, melancholy",
        src:'./assets/audios/51.mp3 ',
    },
      {
        id: "52",
        quebec: "Avoir le coeur gros",
        french: " Etre triste",
        english: "To be sad",
        src:'./assets/audios/52.mp3 ',
    },
      {
        id: "53",
        quebec: "Avoir le feu au cul",
        french: " Etre fâché, désagréable",
        english: "to be angry, disagreeable",
        src:'./assets/audios/53.mp3 ',
    },
      {
        id: "54",
        quebec: "Avoir les shakes",
        french: " Avoir très peur",
        english: "Be very scared",
        src:'./assets/audios/54.mp3 ',
    },
      {
        id: "55",
        quebec: "Avoir les mains plein de pouces",
        french: " Ne pas être habile de ses mains",
        english: " Not being good with your hands",
        src:'./assets/audios/55.mp3 ',
    },
      {
        id: "56",
        quebec: "Avoir une crotte sur le coeur",
        french: " En vouloir à quelqu’un, avoir de la rancune",
        english: " resent someone, hold a grudge",
        src:'./assets/audios/56.mp3 ',
    },
      {
        id: "57",
        quebec: "Avoir un air de beu (boeuf)",
        french: " Être de mauvaise humeur",
        english: "To be in a bad mood",
        src:'./assets/audios/57.mp3 ',
    },
      {
        id: "58",
        quebec: "Avoir une patate chaude dans la bouche",
        french: " Ne pas articuler ou ne rien comprendre quand on parle",
        english: "Not articulating or not understanding anything when speaking",
        src:'./assets/audios/58.mp3 ',
    },
      {
        id: "59",
        quebec: "Avoir une poignée dans le dos",
        french: " Se faire prendre pour une personne stupide",
        english: "To be taken for a stupid person",
        src:'./assets/audios/59.mp3 ',
    },
      {
        id: "60",
        quebec: "Branler dans le manche",
        french: " ne pas être capable de prendre de décisions",
        english: " not being able to make decisions",
        src:'./assets/audios/60.mp3 ',
    },
      {
        id: "61",
        quebec: "Ça me bouillonne dans le fond de la flûte",
        french: " Avoir une envie urgente d’aller aux toilettes",
        english: " Having an urge to go to the toilet",
        src:'./assets/audios/61.mp3 ',
    },
      {
        id: "62",
        quebec: "Ecrire (faire) à mitaine",
        french: " Faire à la main",
        english: "make by hand",
        src:'./assets/audios/62.mp3 ',
    },
      {
        id: "63",
        quebec: "En criant lapin",
        french: " En un rien de temps",
        english: " In no time",
        src:'./assets/audios/63.mp3 ',
    },
      {
        id: "64",
        quebec: "Fou comme un balai",
        french: " Être content",
        english: "Be happy",
        src:'./assets/audios/64.mp3 ',
    },
      {
        id: "65",
        quebec: "Elle veut son biscuit ou son bonbon",
        french: "  elle veut avoir une relation sexuelle",
        english: "she wants to have sex",
        src:'./assets/audios/65.mp3 ',
    },
      {
        id: "66",
        quebec: "Jouer aux fesses",
        french: "  avoir une relation sexuelle",
        english: "have sex",
        src:'./assets/audios/66.mp3 ',
    },
      {
        id: "67",
        quebec: "Grosse Corvette, p’tite quéquette",
        french: "  ça dit ce que ça veut dire que les hommes avec un petit pénis compense par l’achat d’une grosse voiture",
        english: "it says what it means that men with a small penis compensate by buying a big car",
        src:'./assets/audios/67.mp3 ',
    },
      {
        id: "68",
        quebec: "Accouche qu’on baptise",
        french: " Dis tout de suite ce que tu as à dire",
        english: "Say right now what you have to say",
        src:'./assets/audios/68.mp3 ',
    },
      {
        id: "69",
        quebec: "À m’ment d’né",
        french: " à un moment donné",
        english: "at one point",
        src:'./assets/audios/69.mp3 ',
    },
      {
        id: "70",
        quebec: "L’affaire est ketchup",
        french: " La situation est au mieux",
        english: "The situation is at its best",
        src:'./assets/audios/70.mp3 ',
    },
      {
        id: "71",
        quebec: "Agace-pissette",
        french: " Correspond à ce que l’on surnomme une allumeuse dans l’hexagone",
        english: " Corresponds to what is nickquebecd a tease in France",
        src:'./assets/audios/71.mp3 ',
    },
      {
        id: "72",
        quebec: "Aller aux vues ",
        french: " Aller au cinéma",
        english: "Go to the cinema",
        src:'./assets/audios/72.mp3 ',
    },
      {
        id: "73",
        quebec: "Aller sur le trône ",
        french: " Aller aux toilettes",
        english: "Go to the toilet",
        src:'./assets/audios/73.mp3 ',
    },
      {
        id: "74",
        quebec: "Ambitionner su’l’pain béni ",
        french: "  abuser d’une situation avantageuse",
        english: "abuse a position of advantage",
        src:'./assets/audios/74.mp3 ',
    },
      {
        id: "75",
        quebec: "Avoir des bidoux ",
        french: " Avoir beaucoup d’argent",
        english: "To have lots of money",
        src:'./assets/audios/75.mp3 ',
    },
      {
        id: "76",
        quebec: "Avoir du foin ",
        french: " Avoir de l’argent, être riche",
        english: "To have money, to be rich",
        src:'./assets/audios/76.mp3 ',
    },
      {
        id: "77",
        quebec: "Avoir l’air smatte ",
        french: " Personne qui a l’air stupide",
        english: "person who looks stupid",
        src:'./assets/audios/77.mp3 ',
    },
      {
        id: "78",
        quebec: "Avoir le mal de bloc ",
        french: " Personne qui a mal à la tête",
        english: "person with headache",
        src:'./assets/audios/78.mp3 ',
    },
      {
        id: "79",
        quebec: "Avoir les yeux dans l’eau ",
        french: " Avoir l’air triste",
        english: "look sad",
        src:'./assets/audios/79.mp3 ',
    },
      {
        id: "80",
        quebec: "Beurrer épais ",
        french: " Exagérer une situation",
        english: "Exaggerate a situation",
        src:'./assets/audios/80.mp3 ',
    },
      {
        id: "81",
        quebec: "Chanter la pomme ",
        french: " Draguer une personne",
        english: "Pick up a person",
        src:'./assets/audios/81.mp3 ',
    },
      {
        id: "82",
        quebec: "C’est un beau bébé ",
        french: " Dire qu’une fille est belle",
        english: "say a girl is beautiful",
        src:'./assets/audios/82.mp3 ',
    },
      {
        id: "83",
        quebec: "Crisser son camp ",
        french: " Partir",
        english: "To leave",
        src:'./assets/audios/83.mp3 ',
    },
      {
        id: "84",
        quebec: "Être rendu au boutte ",
        french: " Être épuisé ou être plus capable",
        english: "Being exhausted or being more capable",
        src:'./assets/audios/84.mp3 ',
    },
      {
        id: "85",
        quebec: "Être beau (ou belle) comme un coeur ",
        french: " Etre très joli(e)",
        english: "To be very pretty",
        src:'./assets/audios/85.mp3 ',
    },
      {
        id: "86",
        quebec: "Être chaud ou être rond ",
        french: " Être ivre",
        english: "To get drunk",
        src:'./assets/audios/86.mp3 ',
    },
      {
        id: "87",
        quebec: "Être chicken ",
        french: " Être peureux",
        english: "to be fearful",
        src:'./assets/audios/87.mp3 ',
    },
      {
        id: "88",
        quebec: "Être en criss ",
        french: " Etre faché",
        english: "To be angry",
        src:'./assets/audios/88.mp3 ',
    },
      {
        id: "89",
        quebec: "Être tombé en bas de sa chaise ",
        french: " Les bras m’en tombent",
        english: "My arms fall away",
        src:'./assets/audios/89.mp3 ',
    },
      {
        id: "90",
        quebec: "Faire faire un rapport au bébé ",
        french: " Un rot",
        english: "A burp",
        src:'./assets/audios/90.mp3 ',
    },
      {
        id: "91",
        quebec: "Faire la baboune ",
        french: " faire la tête ou faire la gueule",
        english: "sulk or sulk",
        src:'./assets/audios/91.mp3 ',
    },
      {
        id: "92",
        quebec: "Faire le bébé-la-la ",
        french: " Faire le gamin",
        english: "play the kid",
        src:'./assets/audios/92.mp3 ',
    },
      {
        id: "93",
        quebec: "Fermer sa trappe ",
        french: " se taire",
        english: " to shut up",
        src:'./assets/audios/93.mp3 ',
    },
      {
        id: "94",
        quebec: "Fin de semaine ",
        french: " C’est le Week-end",
        english: " It's the weekend",
        src:'./assets/audios/94.mp3 ',
    },
      {
        id: "95",
        quebec: "C’est du vrai gaz d’avion ",
        french: " Liquide fort",
        english: "strong liquid",
        src:'./assets/audios/95.mp3 ',
    },
      {
        id: "96",
        quebec: "J’ai vu neiger avant toi ",
        french: " Avoir plus d’expérience que la personne",
        english: "Have more experience than the person",
        src:'./assets/audios/96.mp3 ',
    },
      {
        id: "97",
        quebec: "J’en ai en masse ou j’en ai un char puis une barge ",
        french: " J’en ai beaucoup",
        english: "I have a lot",
        src:'./assets/audios/97.mp3 ',
    },
      {
        id: "98",
        quebec: "Je suis tanné ",
        french: " J’en ai marre",
        english: "I've had it up to here",
        src:'./assets/audios/98.mp3 ',
    },
      {
        id: "99",
        quebec: "Jeter de la poudre aux yeux ",
        french: " Impressionner",
        english: "Impress",
        src:'./assets/audios/99.mp3 ',
    },
      {
        id: "100",
        quebec: "Le chèque est dans la malle ",
        french: " Le chèque est partit à la poste",
        english: "The check went to the post office",
        src:'./assets/audios/100.mp3 ',
    },
      {
        id: "101",
        quebec: "Le yable l’emporte ",
        french: " Que le diable l’emporte",
        english: "The devil take it",
        src:'./assets/audios/101.mp3 ',
    },
      {
        id: "102",
        quebec: "Mettre la charrue avant les boeufs ",
        french: " Allez trop vite pour faire une action",
        english: "Go too fast to do an action",
        src:'./assets/audios/102.mp3 ',
    },
      {
        id: "103",
        quebec: "Musique à bouche ",
        french: " harmonica",
        english: " harmonica",
        src:'./assets/audios/103.mp3 ',
    },
      {
        id: "104",
        quebec: "Mouillé jusqu’au os ",
        french: " trempé",
        english: " soaked",
        src:'./assets/audios/104.mp3 ',
    },
      {
        id: "105",
        quebec: "Ne pas être achalé ",
        french: " Ne pas avoir froid aux yeux, être sans gêne",
        english: "Do not be cold-eyed, be without embarrassment",
        src:'./assets/audios/105.mp3 ',
    },
      {
        id: "106",
        quebec: "Nourris bien ton cochon, il viendra chier sur ton perron ",
        french: " sera peu reconnaissant",
        english: " will be ungrateful",
        src:'./assets/audios/106.mp3 ',
    },
      {
        id: "107",
        quebec: "Pas de chicane dans ma cabane ",
        french: " pas de dispute",
        english: "no argument",
        src:'./assets/audios/107.mp3 ',
    },
      {
        id: "108",
        quebec: "Passer dans le beurre ",
        french: " Manquer son coup",
        english: "miss his shot",
        src:'./assets/audios/108.mp3 ',
    },
      {
        id: "109",
        quebec: "Prendre ça mollo ",
        french: " ne pas s’énerver",
        english: " don't get upset",
        src:'./assets/audios/109.mp3 ',
    },
      {
        id: "110",
        quebec: "Péter le feu ",
        french: " être en grande forme",
        english: " be in great shape",
        src:'./assets/audios/110.mp3 ',
    },
      {
        id: "111",
        quebec: "Percer des dents ",
        french: " s’énerver sans raison",
        english: "get angry for no reason",
        src:'./assets/audios/111.mp3 ',
    },
      {
        id: "112",
        quebec: "Ptit maudit ",
        french: " Petit vilain",
        english: "little naughty",
        src:'./assets/audios/112.mp3 ',
    },
      {
        id: "113",
        quebec: "Partir comme un petit poulet ",
        french: " mourir tout doucement",
        english: " die slowly",
        src:'./assets/audios/113.mp3 ',
    },
      {
        id: "114",
        quebec: "Les deux bras m’ont tombé ",
        french: " Etre complètement dépassé",
        english: "To be completely overwhelmed",
        src:'./assets/audios/114.mp3 ',
    },
      {
        id: "115",
        quebec: "Lâcher un call ",
        french: " Passer un coup de fil",
        english: "Make a phone call",
        src:'./assets/audios/115.mp3 ',
    },
      {
        id: "116",
        quebec: "Rêver en couleurs ",
        french: " voir trop grand",
        english: " think too big",
        src:'./assets/audios/116.mp3 ',
    },
      {
        id: "117",
        quebec: "Rare comme d’la marde de pape ",
        french: " difficile à trouver",
        english: " hard to find",
        src:'./assets/audios/117.mp3 ',
    },
      {
        id: "118",
        quebec: "Se poigner le moine ",
        french: " ne rien faire, perdre son temps",
        english: " do nothing, waste your time",
        src:'./assets/audios/118.mp3 ',
    },
      {
        id: "119",
        quebec: "Se faire passer un sapin ",
        french: " on lui a fait croire des choses",
        english: " he was made to believe things",
        src:'./assets/audios/119.mp3 ',
    },
      {
        id: "120",
        quebec: "Se faire brasser le canadien ",
        french: " se faire engueuler vivement",
        english: " get yelled at",
        src:'./assets/audios/120.mp3 ',
    },
      {
        id: "121",
        quebec: "Se coucher à l’heure des poules ",
        french: " se coucher très tôt",
        english: " go to bed very early",
        src:'./assets/audios/121.mp3 ',
    },
      {
        id: "122",
        quebec: "T’es pognée avec moé ",
        french: " Tu es prit avec moi",
        english: "You are taken with me",
        src:'./assets/audios/122.mp3 ',
    },
      {
        id: "123",
        quebec: "Tourner autour du pot ",
        french: " ne pas aller droit au but",
        english: " not going straight to the point",
        src:'./assets/audios/123.mp3 ',
    },
      {
        id: "124",
        quebec: "Tomber raide mort ",
        french: " être très fatigué",
        english: " to be very tired",
        src:'./assets/audios/124.mp3 ',
    },
      {
        id: "125",
        quebec: "Tu m’niaises ",
        french: " Tu te moques de moi",
        english: "Are you kidding me",
        src:'./assets/audios/125.mp3 ',
    },
      {
        id: "126",
        quebec: "Tu me tire la pipe (Tirer la pipe à quelqu’un) ",
        french: " Faire une blague",
        english: "To make a joke",
        src:'./assets/audios/126.mp3 ',
    },
      {
        id: "127",
        quebec: "Tu veux tu ",
        french: " est ce que tu veux",
        english: " do you want",
        src:'./assets/audios/127.mp3 ',
    },
      {
        id: "128",
        quebec: "Un fou dans une poche ",
        french: " opportunité facile à prendre",
        english: " easy to take opportunity",
        src:'./assets/audios/128.mp3 ',
    },
      {
        id: "129",
        quebec: "Vouloir son biscuit ",
        french: " désirer une relation sexuelle",
        english: " want a sexual relationship",
        src:'./assets/audios/129.mp3 ',
    },
      {
        id: "130",
        quebec: "Va jouer dans l’trafic ! ",
        french: " va-t-en !",
        english: " go away !",
        src:'./assets/audios/130.mp3 ',
    },
      {
        id: "131",
        quebec: "Y fait pas frette ",
        french: " Il fait chaud",
        english: "It's hot",
        src:'./assets/audios/131.mp3 ',
    },
      {
        id: "132",
        quebec: "Y va manger ses bas ",
        french: " Il va avoir des problèmes ou de la difficulté",
        english: "He is going to have problems or difficulty",
        src:'./assets/audios/132.mp3 ',
    },
      {
        id: "133",
        quebec: "Y va avoir du monde à la messe ",
        french: " une foule",
        english: " a crowd",
        src:'./assets/audios/133.mp3 ',
    },
      {
        id: "134",
        quebec: "Y’a pas d’quoi sauter au plafond ",
        french: " il n’y a pas matière à s’énerver",
        english: " there is nothing to be upset about",
        src:'./assets/audios/134.mp3 ',
    },
      {
        id: "135",
        quebec: "Longue distance ",
        french: " C’est un appel interurbain",
        english: " It's a long distance call",
        src:'./assets/audios/135.mp3 ',
    },
      {
        id: "136",
        quebec: "Matante, mononc’ ",
        french: " Ma tante et mon oncle",
        english: " my aunt and uncle",
        src:'./assets/audios/136.mp3 ',
    },
      {
        id: "137",
        quebec: "Papier cul ",
        french: " papier toilette",
        english: "toilet paper",
        src:'./assets/audios/137.mp3 ',
    },
      {
        id: "138",
        quebec: "Recevoir à la bonne franquette ",
        french: " recevoir des gens à la maison sans cérémonie",
        english: "receive people at home without ceremony",
        src:'./assets/audios/138.mp3 ',
    },
      {
        id: "139",
        quebec: "Ruine babine ",
        french: " Une harmonica",
        english: "A harmonica",
        src:'./assets/audios/139.mp3 ',
    },
      {
        id: "140",
        quebec: "Trouver chaussure à son pied ",
        french: " trouver le partenaire qui nous convient",
        english: " find the right partner",
        src:'./assets/audios/140.mp3 ',
    },
      {
        id: "141",
        quebec: "Torcher les petits ",
        french: " prendre soin des enfants",
        english: " take care of children",
        src:'./assets/audios/141.mp3 ',
    },
      {
        id: "142",
        quebec: "Accrocher ses patins ",
        french: " Démissionner",
        english: "To resign",
        src:'./assets/audios/142.mp3 ',
    },
      {
        id: "143",
        quebec: "Avoir l’air d’un chien savant ",
        french: " Passé pour une personne intelligente",
        english: "Passed for an intelligent person",
        src:'./assets/audios/143.mp3 ',
    },
      {
        id: "144",
        quebec: "Carte d’affaires ",
        french: " C’est une carte de visite",
        english: " It's a business card",
        src:'./assets/audios/144.mp3 ',
    },
      {
        id: "145",
        quebec: "Je suis loadé ou je suis dans le jus ",
        french: " Avoir beaucoup de chose / travail à faire",
        english: "Have a lot of stuff/work to do",
        src:'./assets/audios/145.mp3 ',
    },
      {
        id: "146",
        quebec: "Mise à pied ",
        french: " C’est un licenciement",
        english: " It's a dismissal",
        src:'./assets/audios/146.mp3 ',
    },
      {
        id: "147",
        quebec: "Shack à patate ",
        french: " Cantine",
        english: "Canteen",
        src:'./assets/audios/147.mp3 ',
    },
      {
        id: "148",
        quebec: "Sous-ministre ",
        french: " Le secrétaire général d’un ministre",
        english: " The general secretary of a minister",
        src:'./assets/audios/148.mp3 ',
    },
      {
        id: "149",
        quebec: "Aller gazer ",
        french: " Faire le plein, mettre de l’essence dans sa voiture",
        english: " Fill up, put gas in your car",
        src:'./assets/audios/149.mp3 ',
    },
      {
        id: "150",
        quebec: "Bon trip ",
        french: " Bon voyage",
        english: "Have a good trip",
        src:'./assets/audios/150.mp3 ',
    },
      {
        id: "151",
        quebec: "Break à bras ",
        french: " Un frein à main",
        english: "A handbrake",
        src:'./assets/audios/151.mp3 ',
    },
      {
        id: "152",
        quebec: "Brûler une lumière rouge ",
        french: " passer sur le feu rouge de circulation",
        english: " pass on the red traffic light",
        src:'./assets/audios/152.mp3 ',
    },
      {
        id: "153",
        quebec: "Partir le char ",
        french: " Démarrer la voiture",
        english: " Start the car",
        src:'./assets/audios/153.mp3 ',
    },
      {
        id: "154",
        quebec: "Patins à roues alignées ",
        french: " Ce sont les rollers",
        english: " These are the rollerblades",
        src:'./assets/audios/154.mp3 ',
    },
      {
        id: "155",
        quebec: "Souffler dans la balloune ",
        french: " passer un test alcool quand on est en voiture ou moto",
        english: " pass an alcohol test when you are in a car or motorbike",
        src:'./assets/audios/155.mp3 ',
    },
      {
        id: "156",
        quebec: "Slaque la pédale ",
        french: " relâcher l’accélérateur",
        english: " release the accelerator",
        src:'./assets/audios/156.mp3 ',
    },
      {
        id: "157",
        quebec: "Virage en U ",
        french: " C’est un demi-tour",
        english: " It's a half-turn",
        src:'./assets/audios/157.mp3 ',
    },
      {
        id: "158",
        quebec: "Virer sur un dix cennes ",
        french: " changer de direction rapidement",
        english: " change direction quickly",
        src:'./assets/audios/158.mp3 ',
    },
      {
        id: "159",
        quebec: "Vieille minoune ",
        french: " vieille auto mal en point",
        english: " old car in bad shape",
        src:'./assets/audios/159.mp3 ',
    },
      {
        id: "160",
        quebec: "Avoir de l’eau dans sa cave ",
        french: " Avoir un pantalon trop court",
        english: " Have pants that are too short",
        src:'./assets/audios/160.mp3 ',
    },
      {
        id: "161",
        quebec: "Abrier ou habriller ",
        french: " Se couvrir",
        english: "To cover",
        src:'./assets/audios/161.mp3 ',
    },
      {
        id: "162",
        quebec: "Avoir la flye à l’air ",
        french: " Avoir la braguette ouverte",
        english: " Have the fly open",
        src:'./assets/audios/162.mp3 ',
    },
      {
        id: "163",
        quebec: "Faire dur ",
        french: " Avoir une apparence déplaisante ou misérable",
        english: "Having an unpleasant or miserable appearance",
        src:'./assets/audios/163.mp3 ',
    },
      {
        id: "164",
        quebec: "Se mettre beau ou belle ",
        french: " Être chic",
        english: " be classy",
        src:'./assets/audios/164.mp3 ',
    },
      {
        id: "165",
        quebec: "Se mettre sur son 36 ",
        french: " s’habiller de beaux vêtements",
        english: " dress in nice clothes",
        src:'./assets/audios/165.mp3 ',
    },
      {
        id: "166",
        quebec: "Ton magasin est ouvert ",
        french: " ta fermeture éclair est ouverte",
        english: " your zipper is open",
        src:'./assets/audios/166.mp3 ',
    },
      {
        id: "167",
        quebec: "C’est pas piquer des vers ",
        french: " C’est très bon",
        english: " It's very good",
        src:'./assets/audios/167.mp3 ',
    },
      {
        id: "168",
        quebec: "Chien-chaud ",
        french: " C’est la traduction littérale du hot-dog",
        english: " This is the literal translation of hot dog",
        src:'./assets/audios/168.mp3 ',
    },
      {
        id: "169",
        quebec: "Patates frites ",
        french: " Ce sont des frites",
        english: " These are fries",
        src:'./assets/audios/169.mp3 ',
    },
      {
        id: "170",
        quebec: "Patates pilées ",
        french: " C’est une purée de pommes de terre",
        english: " It's mashed potatoes",
        src:'./assets/audios/170.mp3 ',
    },
      {
        id: "171",
        quebec: "Pâté chinois ",
        french: " C’est notre bon vieux  hachis Parmentier mais avec du maïs",
        english: " It's our good old shepherd's pie but with corn",
        src:'./assets/audios/171.mp3 ',
    },
      {
        id: "172",
        quebec: "Se sucrer le bec ",
        french: " manger quelque chose de sucré",
        english: " eat something sweet",
        src:'./assets/audios/172.mp3 ',
    },
      {
        id: "173",
        quebec: "Se bourrer la fraise ",
        french: " manger à satiété",
        english: " eat to satiety",
        src:'./assets/audios/173.mp3 ',
    },
      {
        id: "174",
        quebec: "Sous-marin ",
        french: " C’est un sandwich allongé",
        english: " It's an elongated sandwich",
        src:'./assets/audios/174.mp3 ',
    },
      {
        id: "175",
        quebec: "Tire d’érable ",
        french: " C’est le sirop de sève qui forme un caramel",
        english: " It is the sap syrup that forms a caramel",
        src:'./assets/audios/175.mp3 ',
    },
      {
        id: "176",
        quebec: "Grand parleur, p’tit faiseur ",
        french: " Quelqu’un qui parle beaucoup mais agit peu",
        english: "Someone who talks a lot but does little",
        src:'./assets/audios/176.mp3 ',
    },
      {
        id: "177",
        quebec: "Gratte cenne ",
        french: " Un radin",
        english: "A cheapskate",
        src:'./assets/audios/177.mp3 ',
    },
      {
        id: "178",
        quebec: "Grosse vie sale ",
        french: " Se la couler douce",
        english: "To take it easy",
        src:'./assets/audios/178.mp3 ',
    },
      {
        id: "179",
        quebec: "J’m’en câlisse comme de l’an 40 ",
        french: " ca ne m’intéresse pas",
        english: " it does not interest me",
        // src:'./assets/audios/179.mp3 ',
    },
      {
        id: "180",
        quebec: "Lâcher un fiouse ",
        french: " péter",
        english: " to fart",
        // src:'./assets/audios/180.mp3 ',
    },
      {
        id: "181",
        quebec: "Méchant brochet ",
        french: " Personne de stupide",
        english: "stupid person",
        src:'./assets/audios/p2.mp3 ',
    },
      {
        id: "182",
        quebec: "Pogne pas les nerfs ",
        french: " Fâche-toi pas",
        english: "Don't be angry",
        src:'./assets/audios/p2.mp3 ',
    },
      {
        id: "183",
        quebec: "Péter une coche ",
        french: " s’ennerver",
        english: " get angry",
        src:'./assets/audios/p2.mp3 ',
    },
      {
        id: "184",
        quebec: "Péter plus haut que le trou ",
        french: " être snob",
        english: " be a snob",
        src:'./assets/audios/p2.mp3 ',
    },
      {
        id: "185",
        quebec: "Rien foutre ou se pogner le cul ",
        french: " Rien faire",
        english: "Do nothing",
        src:'./assets/audios/p2.mp3 ',
    },
      {
        id: "186",
        quebec: "Sans-dessein (Bande de) ",
        french: " Personne qui n’est pas intelligente",
        english: "person who is not intelligent",
        src:'./assets/audios/p2.mp3 ',
    },
      {
        id: "187",
        quebec: "S’exciter le poil des jambes ",
        french: " s’énerver",
        english: " get angry",
        src:'./assets/audios/p2.mp3 ',
    },
      {
        id: "188",
        quebec: "Une face à claque ",
        french: " un visage qui ne nous revient pas",
        english: " a face that does not come back to us",
        src:'./assets/audios/p2.mp3 ',
    },
      {
        id: "189",
        quebec: "Y’é Heavy Metal ",
        french: " personne bizarre",
        english: " weird person",
        src:'./assets/audios/p2.mp3 ',
      }

]

